-- Generated from content/nodes.json and content/cards.json. Fixture content only; draft bundles are excluded.
-- Re-running this file is idempotent.

begin;

insert into public.concept_nodes (id, kind, title, purpose, status, source_refs, maintainer) values
  ('english-fixture-root', 'root', 'English foundations', 'Một bản đồ nhỏ để thử cách học từ nguyên lý.', 'fixture', ARRAY['project-fixture:placeholder-english-v1']::text[], 'hiep'),
  ('english-fixture-recall', 'trunk', 'Recall before recognition', 'Gọi ý ra trước, sau đó mới nhìn lời giải.', 'fixture', ARRAY['project-fixture:placeholder-english-v1']::text[], 'hiep'),
  ('english-fixture-mechanism', 'branch', 'Mechanism & boundaries', 'Không chỉ nhớ câu; hiểu vì sao và khi nào nó không còn đúng.', 'fixture', ARRAY['project-fixture:placeholder-english-v1']::text[], 'hiep'),
  ('english-fixture-transfer', 'leaf', 'Transfer to a fresh example', 'Đưa ý tưởng sang một tình huống mới.', 'fixture', ARRAY['project-fixture:placeholder-english-v1']::text[], 'hiep')
on conflict (id) do update set kind = excluded.kind, title = excluded.title, purpose = excluded.purpose, status = excluded.status, source_refs = excluded.source_refs, maintainer = excluded.maintainer, updated_at = now();

insert into public.concept_edges (from_node_id, to_node_id, edge_type) values
  ('english-fixture-root', 'english-fixture-recall', 'part_of'),
  ('english-fixture-recall', 'english-fixture-mechanism', 'prerequisite'),
  ('english-fixture-mechanism', 'english-fixture-transfer', 'prerequisite')
on conflict (from_node_id, to_node_id, edge_type) do nothing;

insert into public.cards (id, node_id, card_type, prompt, model_answer, explanation, misconception, transfer_prompt, prerequisite_node_ids, source_refs, status, author, reviewer) values
  ('fixture-recall-01', 'english-fixture-recall', 'core_recall', 'Trong câu, một verb thường làm công việc gì? Hãy nói bằng lời của bạn.', 'Verb thường diễn tả hành động, sự việc, hoặc trạng thái của chủ thể.', 'Nhìn vào vai trò giúp ta nhận ra verb kể cả khi hình thức của nó thay đổi.', 'Verb lúc nào cũng là một hành động nhìn thấy được.', 'Trong câu ‘She seems tired’, từ nào đang diễn tả trạng thái? Vì sao?', ARRAY[]::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-recall-02', 'english-fixture-recall', 'mechanism', 'Vì sao một verb có thể đổi hình thức theo thời gian hoặc chủ thể?', 'Hình thức của verb mang thêm thông tin ngữ pháp như thời gian hoặc sự hòa hợp với chủ thể.', 'Phần thay đổi không chỉ là trang trí; nó giúp người nghe định vị sự việc trong câu.', 'Mọi thay đổi hình thức của verb đều tạo ra một từ vựng mới.', 'So sánh ‘I walk’ và ‘She walks’: phần nào đổi và thông tin nào được thêm?', ARRAY['english-fixture-recall']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-recall-03', 'english-fixture-recall', 'contrast', 'Verb khác noun ở điểm chức năng nào trong câu? Đừng chỉ nêu ví dụ.', 'Verb làm trung tâm của sự việc hoặc trạng thái; noun gọi tên người, vật, nơi chốn, hoặc ý niệm.', 'Phân biệt theo công việc trong câu bền hơn việc học thuộc một danh sách hậu tố.', 'Từ dài là noun còn từ ngắn là verb.', 'Trong ‘A quick run helps’, ‘run’ đang làm công việc gì?', ARRAY['english-fixture-recall']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-mechanism-01', 'english-fixture-mechanism', 'mechanism', 'Vì sao câu tiếng Anh thường cần một verb rõ ràng dù câu rất ngắn?', 'Verb cho câu một sự việc hoặc trạng thái để người nghe biết đang nói về điều gì xảy ra.', 'Không có trung tâm sự việc, một nhóm từ dễ chỉ còn là mảnh thông tin chưa hoàn chỉnh.', 'Chỉ cần có noun là đã có một câu hoàn chỉnh.', '‘The quiet room’ thiếu điều gì nếu muốn trở thành một câu? Hãy thêm phần tối thiểu.', ARRAY['english-fixture-recall']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-mechanism-02', 'english-fixture-mechanism', 'boundary', 'Khi nào cách phân loại ‘verb = hành động’ bị hỏng? Nêu một boundary.', 'Nó bị hỏng khi verb diễn tả trạng thái hoặc nhận định, không phải hành động quan sát được.', 'Một nguyên tắc tốt cần boundary để tránh áp dụng quá rộng.', 'Nếu không nhìn thấy chuyển động thì từ đó không thể là verb.', 'Giải thích vì sao ‘know’ hoặc ‘seem’ vẫn là verb trong ngữ cảnh phù hợp.', ARRAY['english-fixture-mechanism']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-mechanism-03', 'english-fixture-mechanism', 'application', 'Nếu muốn nói một việc đang diễn ra ngay lúc này, bạn sẽ kiểm tra cơ chế nào trước?', 'Kiểm tra thời gian và cấu trúc đang diễn ra, rồi chọn hình thức verb phù hợp với chủ thể.', 'Ứng dụng bắt đầu từ ý nghĩa muốn truyền đạt, sau đó mới chọn hình thức.', 'Cứ thêm ‘-ing’ vào verb là đủ cho mọi câu về hiện tại.', 'Tự tạo một câu mô tả việc đang diễn ra và giải thích vì sao bạn chọn cấu trúc đó.', ARRAY['english-fixture-mechanism']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-transfer-01', 'english-fixture-transfer', 'application', 'Trong một tình huống mới, bạn sẽ dùng ‘why’ để kiểm tra một câu tiếng Anh như thế nào?', 'Hỏi vì sao mỗi từ và hình thức của nó xuất hiện; câu trả lời phải nối được chức năng với ý nghĩa.', 'Câu hỏi ‘why’ giúp chuyển từ nhận diện mẫu sang hiểu cơ chế tạo ra mẫu.', 'Chỉ cần câu nghe quen tai là đã hiểu vì sao nó đúng.', 'Chọn một câu bạn từng viết và giải thích một lựa chọn verb bằng ‘why’.', ARRAY['english-fixture-mechanism']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-transfer-02', 'english-fixture-transfer', 'production', 'Tạo một câu tiếng Anh có một verb diễn tả trạng thái, rồi giải thích cơ chế của nó.', 'Ví dụ: ‘They know the answer.’ ‘Know’ diễn tả trạng thái nhận thức của chủ thể.', 'Tự sản xuất câu cho thấy learner có thể chuyển nguyên tắc sang ngữ cảnh khác.', 'Một verb chỉ hợp lệ nếu nó mô tả chuyển động.', 'Đổi chủ thể hoặc trạng thái trong câu vừa tạo mà vẫn giữ cơ chế.', ARRAY['english-fixture-mechanism']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-transfer-03', 'english-fixture-transfer', 'contrast', 'Khi sửa một câu, bạn phân biệt ‘sai ngữ pháp’ với ‘không hợp ngữ cảnh’ ra sao?', 'Kiểm tra cấu trúc trước, rồi kiểm tra ý nghĩa và tình huống; một câu có thể đúng cấu trúc nhưng không phù hợp ý định.', 'Tách hai câu hỏi giúp không sửa máy móc một câu chỉ vì nó khác mẫu quen thuộc.', 'Mọi câu nghe lạ đều sai ngữ pháp.', 'Viết một câu đúng cấu trúc nhưng không hợp một tình huống cụ thể.', ARRAY['english-fixture-mechanism']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-foundation-01', 'english-fixture-recall', 'core_recall', 'Thế nào là một câu trả lời có mechanism thay vì chỉ lặp lại định nghĩa?', 'Nó nối nguyên nhân hoặc cấu trúc với kết quả, để người học giải thích được vì sao điều đó xảy ra.', 'Mechanism là cây cầu từ ‘cái gì’ sang ‘vì sao’.', 'Trả lời dài hơn luôn có nghĩa là đã giải thích cơ chế.', 'Lấy một quy tắc quen thuộc và thêm một mệnh đề ‘vì sao’.', ARRAY[]::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-foundation-02', 'english-fixture-recall', 'boundary', 'Vì sao một nguyên tắc học tiếng Anh nên có counterexample?', 'Counterexample cho thấy ranh giới áp dụng, giúp người học không biến quy tắc hữu ích thành công thức tuyệt đối.', 'Nhìn thấy nơi quy tắc không áp dụng là một phần của hiểu sâu.', 'Counterexample chỉ làm người mới học rối hơn nên có thể bỏ qua.', 'Nêu một câu khiến quy tắc ‘verb = hành động’ không còn đủ chính xác.', ARRAY['english-fixture-recall']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep'),
  ('fixture-foundation-03', 'english-fixture-transfer', 'production', 'Hãy dạy lại cho một người bạn cách học một card mà không cho họ xem đáp án trước.', 'Đưa prompt trước, yêu cầu họ tự gọi ý ra, sau đó mới cho xem đáp án và hỏi họ tự đánh giá Nhớ hoặc Quên.', 'Cách dạy lại giữ nguyên thứ tự recall → feedback → self-grade.', 'Cho xem đáp án trước sẽ tiết kiệm thời gian và chứng minh đã học.', 'Thiết kế một prompt mở cho một ý tưởng khác mà bạn đang học.', ARRAY['english-fixture-transfer']::text[], ARRAY['project-fixture:placeholder-english-v1']::text[], 'published', 'project', 'hiep')
on conflict (id) do update set node_id = excluded.node_id, card_type = excluded.card_type, prompt = excluded.prompt, model_answer = excluded.model_answer, explanation = excluded.explanation, misconception = excluded.misconception, transfer_prompt = excluded.transfer_prompt, prerequisite_node_ids = excluded.prerequisite_node_ids, source_refs = excluded.source_refs, status = excluded.status, author = excluded.author, reviewer = excluded.reviewer, updated_at = now();

commit;
